"""Constants for vista component."""
DOMAIN = "vista_control"
SERVERS = "servers"
DEVICES = "devices"
ENTITIES = "entities"
SERVICE_UPDATE = "update"
ATTRIBUTION = "Vista"
CONNECTION = "connection"
MANUFACTURER = "Vista"
MODEL = "128bpt"
